---
- hosts: webserver
  remote_user: ec2-user
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Install EPEL release for nginx
    yum: name=epel-release state=present


  tasks:
  - name: Install nginx
    yum:
       name: nginx
       state: present
  - service:
       name: nginx
       state: started
       enabled: yes

