---
- hosts: lb
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      yum: name=python-pip state=present

    - name: install docker-py package
      pip: name=docker-py

    - name: install docker
      yum: name=docker

    - name: Ensure service is enabled
      command: service docker restart
