# ansible-vault edit aws-credentials.yml
# ansible-vault create ino/aws-credentials.yml
# ansible-playbook provision.yml --ask-vault-pass --tags create_ec2
# Goto aws iam service and generate promming user with adminaceess policy is required either full admin access or ec2 admin access to user
AWS_ACCESS_KEY_ID: AXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
